name: Run Discord Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 20 minutes
  workflow_dispatch:  # Allows manual triggering


jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # You can use 3.10 or 3.12 if needed

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Run the bot
      env:
        TOKEN: ${{ secrets.TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        PROFILE_URL: ${{ secrets.PROFILE_URL }}
      run: |
        python bot.py