name: Run Discord Bot

on:
  schedule:
     # For Daylight Saving Time (UTC+1)
    # Uncomment the following lines if in Daylight Saving Time
    - cron: '*/5 08-09 * * *'   # Every 5 minutes from 09:00 to 10:00 WEST
    - cron: '*/5 17-22 * * *'   # Every 5 minutes from 18:00 to 23:59 WEST
    - cron: '*/5 00-02 * * *'   # Every 5 minutes from 00:00 to 02:00 WEST
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # You can use 3.10 or 3.12 if needed

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Run the bot
      env:
        TOKEN: ${{ secrets.TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        PROFILE_URL: ${{ secrets.PROFILE_URL }}
      run: |
        python bot.py