name: Run Discord Bot

on:
  schedule:
    - cron: '*/5 16-17 * * *'  # Every 5 minutes from 09:00 AM to 10:00 AM PT
    - cron: '*/5 01-10 * * *'  # Every 5 minutes from 06:00 PM to 03:00 AM PT
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # You can use 3.10 or 3.12 if needed

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Run the bot
      env:
        TOKEN: ${{ secrets.TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        PROFILE_URL: ${{ secrets.PROFILE_URL }}
      run: |
        python bot.py